### ISSUE TITLE
how to use this mod

### ISSUE THREAD

**Issue by MXP2095onetechguy** [VisualError/GoosePresence#1]
I have installed this mod, but how to use it?
it is not showing up on my discord

**Comment by VisualError** [comment]
Are you using Discord web instead of the Desktop Application? If so you have to use the App instead of the website as the site doesn't support rich presence, if you are using the Desktop Application check if you have your game activity enabled in your Discord settings.
If it still doesn't work, make sure that Desktop Goose mods are working for you.
